/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GraderRouteImport } from './routes/grader'
import { Route as MinerRouteImport } from './routes/miner'
import { Route as ProtocolRouteImport } from './routes/protocol'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GraderRoute = GraderRouteImport.update({
  id: '/grader',
  path: '/grader',
  getParentRoute: () => rootRouteImport,
} as any)
const MinerRoute = MinerRouteImport.update({
  id: '/miner',
  path: '/miner',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtocolRoute = ProtocolRouteImport.update({
  id: '/protocol',
  path: '/protocol',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/grader': typeof GraderRoute
  '/miner': typeof MinerRoute
  '/protocol': typeof ProtocolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/grader': typeof GraderRoute
  '/miner': typeof MinerRoute
  '/protocol': typeof ProtocolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/grader': typeof GraderRoute
  '/miner': typeof MinerRoute
  '/protocol': typeof ProtocolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/grader' | '/miner' | '/protocol'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/grader' | '/miner' | '/protocol'
  id: '__root__' | '/' | '/grader' | '/miner' | '/protocol'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GraderRoute: typeof GraderRoute
  MinerRoute: typeof MinerRoute
  ProtocolRoute: typeof ProtocolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grader': {
      id: '/grader'
      path: '/grader'
      fullPath: '/grader'
      preLoaderRoute: typeof GraderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/miner': {
      id: '/miner'
      path: '/miner'
      fullPath: '/miner'
      preLoaderRoute: typeof MinerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protocol': {
      id: '/protocol'
      path: '/protocol'
      fullPath: '/protocol'
      preLoaderRoute: typeof ProtocolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GraderRoute: GraderRoute,
  MinerRoute: MinerRoute,
  ProtocolRoute: ProtocolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
